export WEBAPI_URL="http://127.0.0.1:8081"
export CONTAINER_NAME="/bigdata"
export DRIVERS_TABLE="/taxi_example/drivers/"
export PASSENGERS_TABLE="/taxi_example/passengers/"
export CELLS_TABLE="/taxi_example/cells/"
